### ISSUE TITLE
Outdated postgres chart dependency

### ISSUE THREAD

**Issue by shishkin** [goauthentik/helm#109]
It seems that the used postgres chart version (10.16.2) is outdated compared to [latest release](https://artifacthub.io/packages/helm/bitnami/postgresql) (12.1.3) by two major versions.

Being new to helm charts I've spent quite some time overriding values according to the latest docs to no avail. Then figure out where the version 10 docs are because bitnami repo is a monorepo with no apparent tagging consistency. These are of course my own problems of not knowing the ecosystem enough or issues one should address to bitnami org. Though it would be beneficial to newcomers to at least use the latest version of chart dependencies with links to respective docs of how to override common configuration.

Are there any blockers to update to the latest postgres chart?

**Comment by samip5** [comment]
> Are there any blockers to update to the latest postgres chart?

Yes, those that are using the bundled postgres will more than likely have bad time due to how postgres needs to be upgraded and one cannot probably do it from 10 ->13 so it would more than likely break people's Authentik installs.

**Comment by badsmoke** [comment]
how will an upgrade look like? version 11 is officially marked as obsolete by authentik.

will one update?
will that make the helm chat independently?
is there a step by step guide?

i tried to upgrade today with the help of https://github.com/tianon/docker-postgres-upgrade/issues
but I had no success
