### ISSUE TITLE
helm values for geoip get missparsed as float64

### ISSUE THREAD

**Issue by GeorgeGedox** [goauthentik/helm#170]
**Describe the bug**
Helm values for `geoip` are not parsed properly

**To Reproduce**

1. Use helm
2. Fill in the values for `geoip` `accountId`, `licenseKey` and `updateInterval`

**Expected behavior**
Helm deployment should complete

**Screenshots**

**Logs**
```
Helm upgrade failed: template: authentik/templates/worker-deployment.yaml:28:43: executing "authentik/templates/worker-deployment.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: authentik/templates/secret.yaml:14:93: executing "authentik/templates/secret.yaml" at <b64enc>: wrong type for value; expected string; got float64 Last Helm logs: preparing upgrade for authentik resetting values to the chart's original version
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.5.3
-   Deployment: helm
-   CD: fluxcd

**Additional context**
This issue seems to be very similar to this one https://github.com/helm/helm/issues/2434 where the parsing of numerical values gets confused

**Comment by BeryJu** [comment]
while this could be prevented with adding a "| tostring" before the "| b64enc", this will still cause issues as the number is still interpreted as float. I'm not sure if there's anything that can be done besides requiring that people quote the IDs in their values.yaml to make sure they are interpreted as strings

**Comment by GeorgeGedox** [comment]
Quoting the values is not possible for everyone, for example in my case using flux with variable substitution leads to the final helm release having the raw values for anything that's a number be unquoted and treated as an int. Basically meaning this:
```
accountId: "${SECRET_ACCOUNT_ID}"
```
gets converted to this after processing
```
accountId: 12345678
```

So a way to force the conversion in the helm template would be needed, or accept any kind of format as value and deal with it at application level since the helm yaml preprocessor seems to fail.

**Comment by h3mmy** [comment]
I restructured my geoip secrets into a kubernetes secret like [this](https://github.com/h3mmy/bloopySphere/commit/979c0b5cb23496ee46fb82a8dbafd87b58d49872) It also does not work. The base64 encode/decode will strip out the quotes and render it as a numbe.

The difference was now it's being parsed as an int64 instead of a float64

```
Helm upgrade failed: template: authentik/templates/worker-deployment.yaml:28:43: executing "authentik/templates/worker-deployment.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: authentik/templates/secret.yaml:14:93: executing "authentik/templates/secret.yaml" at <b64enc>: wrong type for value; expected string; got int64
```

**Comment by NigelVanHattum** [comment]
I parsing my ID and licenseKey as a helm parameter. Adding quotes to the parameters allows it to parse without issue

**Comment by rissson** [comment]
Heya! With #230 we're adding the possibility to reference an existing secret instead of having to put those credentials in your values. It should solve those issues.
