### ISSUE TITLE
Update to release Release 2021.8

### ISSUE THREAD

**Issue by btrepp** [goauthentik/helm#19]
Noticed the deploy didn't have the embedded outpost, so was a bit confused following setup.
Looks like this is only in 2021.8, and the chart has 2021.7

Funnily enough the docs imply to just update the helm chart, but I think that hasn't landed yet.

Current workaround for me was 

add in values.yaml
```
image:
  tag: 2021.8.3
```

**Comment by BeryJu** [comment]
There are still a couple of bugs left in the embedded outpost, hence I haven't bumped the image versions yet. Planning to have 8.4 out in a few days, and then I'll create a new version with those images.
