### ISSUE TITLE
No serviceAccount for server-deployment (just worker)

### ISSUE THREAD

**Issue by wrenix** [goauthentik/helm#197]

**Comment by BeryJu** [comment]
This is intended as only the worker connects to the Kubernetes API and the server does not

**Comment by wrenix** [comment]
i need it for my sidecar, till you merge #146 and here you mean, that both need the blueprints: #156

**Comment by BeryJu** [comment]
The blueprints dont need to be mounted on the server anymore since https://github.com/goauthentik/authentik/commit/411ef239f63e4d3beacd8297d4be54b29fb30127

**Comment by wrenix** [comment]
okay, so i need an option for setup additionalContainer only for worker (not server).

i believe that is part of #171
