### ISSUE TITLE
The Redis HPA is no longer supported in the latest version of K8S

### ISSUE THREAD

**Issue by ModdingFriendly** [goauthentik/helm#219]
It looks like the Bitnami Charts that you are using have not been updated to pull in the latest versions of the chart that add support for `autoscaling/v2` with the deprecation of `autoscaling/v2beta1` in v1.22 

It should be a quick merge against the Bitnami charts to fix

**Comment by BeryJu** [comment]
we can probably do this with the 2024.1 helm release since we're already gonna do some breaking changes with that, and the newer bitnami charts all have changed configuration options cc @rissson

**Comment by rissson** [comment]
Yes, we'll look into updating those charts for the 2024.1 release
