### ISSUE TITLE
Bug: Error in 2024.2.0 helm chart ingress

### ISSUE THREAD

**Issue by DrZoidberg09** [goauthentik/helm#240]
When I update my current helm chart to 2024.2.0 I get this error:

> Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "authentik-2022-1659047326-server" is invalid: spec.rules[0].host: Invalid value: "map[host:{hostname} paths:[map[path:/ pathType:Prefix]]]": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

I had to move the ingress section to server as mentioned in the README. Otherwise I did not change anything.

**Comment by rissson** [comment]
The `hosts` list now only expects a list of domains: https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml#L569
