### ISSUE TITLE
2024.4.0 Update - Worker Pod Startup Probe Fails

### ISSUE THREAD

**Issue by noxuum** [goauthentik/helm#263]
**Relevant info**
Kube version: `v1.29.0+k3s1`
Authentik Helm Chart Version: `2024.4.0`

**Version and Deployment**

authentik version: 2024.4.0
Deployment: [helm]

**Issue Description**

After updating the helm chart from `2024.2.3` to `2024.4.0` the worker pods goes into `CrashLoopBackOff` status with the following logs:

```
Warning  Unhealthy  24m  kubelet  Startup probe failed: {"event":"checking health","level":"debug","mode":"worker","timestamp":"2024-04-25T12:56:58Z"}
{"error":"stat /dev/shm/authentik-worker: no such file or directory","event":"failed to check worker heartbeat file","level":"warning","timestamp":"2024-04-25T12:56:58Z"}
```

The only change in the chart I noticed is that `livenessProbe`, `readinessProbe` and `startupProbe` were added to the workers deployment that could be related to this issue.

Thanks in advance for the help!

**Comment by BeryJu** [comment]
we should probably expand the initial delay a bit on the startup probes (since my deployments of the worker all start fine) cc @channel-42

**Comment by noxuum** [comment]
@BeryJu on point, incresing the delay resolved my issue.

Thank you for the quick tip!
