### ISSUE TITLE
can not access inital setup page if email is added in values.yaml

### ISSUE THREAD

**Issue by ksullivan86** [goauthentik/helm#274]
I have tested and confirmed that when I add email to the values.yaml I cannot access the initial setup url but when I start over and don't use any email in the values.yaml I can have no problem and I can access the initial setup page.

**Comment by BeryJu** [comment]
This is intended, if any of the values here: https://docs.goauthentik.io/docs/installation/automated-install are set, authentik assumes an automated install and will disable the initial setup flow
