### ISSUE TITLE
External postgresql secret key typo

### ISSUE THREAD

**Issue by berkerol** [goauthentik/helm#297]
When using external postgresql and specfying password, the key in secret `authentik` should be `AUTHENTIK_POSTGRESQL__PASSWORD` instead of `AUTHENTIK_POSTRESQL__PASSWORD`.

I have to edit secret manually after every time I do helm upgrade. Please fix this. I can't find where are these keys for secret are located. Otherwise I would fix myself.

**Comment by BeryJu** [comment]
The environment variables in the secret are generated based on the helm values, mapping the `authentik` object directly.

**Comment by berkerol** [comment]
Ok so this was my fault. I had a typo in my script. Sorry for inconvenience. Thanks for fast answer.
