### ISSUE TITLE
Support for kubernetes secrets

### ISSUE THREAD

**Issue by gianlazz** [goauthentik/helm#45]
Is this helm chart configured to support using Kubernetes secrets to define the db password & Authentik `secret_key` value? I'd like to check in my config to a repo though am concerned about inadvertently checking in secrets.

**Comment by BeryJu** [comment]
you can already use `envFrom` in the chart to include secrets, which can be used from the environment variables from https://goauthentik.io/docs/installation/configuration/ to configure secret keys etc

**Comment by gianlazz** [comment]
Gotcha thank you, I'll give that a go.

**Comment by Michaelpalacce** [comment]
Can you add a bit more details on how to do this. My values look like:


~~~yaml
env:
        envFrom:
            - secretRef:
                  name: db
            - secretRef:
                  name: smtp
            - secretRef:
                  name: authentik
        ingress:
            enabled: true
            tls:
                - hosts:
                      - "*.stefangenov.site"
                  secretName: ingress
            hosts:
                - host: authentik.stefangenov.site
                  paths:
                      - path: "/"
                        pathType: Prefix
~~~

and this does not work...
