### ISSUE TITLE
`.Values.envValueFrom` is templated incorrectly since 2022.8.2

### ISSUE THREAD

**Issue by gabe565** [goauthentik/helm#85]
As of 2022.8.2, `.Values.envValueFrom` gets templated incorrectly.

If I template a chart with the following in my values.yaml:

```shell
envValueFrom:
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: postgresql
      key: postgres-password
```

The previous chart would create:

```shell
env:
  - name: AUTHENTIK_POSTGRESQL__PASSWORD
    valueFrom:
      secretKeyRef:
        name: PostgreSQL
        key: postgres-password
```

But as of 2022.8.2, the following gets templated

```shell
env:
  - name: "name"
    value: "AUTHENTIK_POSTGRESQL__PASSWORD"
  - name: "valueFrom"
    value: "secretKeyRef:\n  key: postgres-password\n  name: postgresql"
```

It seems like the most straightforward fix would be to revert the env changes, but I don't want to revert them if it was changed for a reason. I am working on a better fix, but much of the env functionality would need to change. Was this modified to fix another issue?

**Comment by BeryJu** [comment]
The actual change itself was made to not directly set secrets into deployments and instead set them in secrets and use those, however the testing setup does not test 100% of the options, hence this issue was missed.

I think the easiest way for now is to just revert that PR
